services:
  - { type: web, name: smart-excel-json-parser, plan: free, repo: https://github.com/Bhavyaa97/smart-file-conversion.git, region: oregon, branch: main, rootDir: ., dockerContext: ., dockerfilePath: ./Dockerfile, envVars: [ { key: PORT, value: 8080 } ], runtime: docker }
